import { RambamMonth, RambamDay } from './types';

// Helper to generate a month range
function generateMonth(id: string, name: string, year: string, daysCount: number, startHebDay: number, dailyTasks: any[]): RambamMonth {
  const HEB_NUMERALS: Record<number, string> = {
    1: 'א', 2: 'ב', 3: 'ג', 4: 'ד', 5: 'ה', 6: 'ו', 7: 'ז', 8: 'ח', 9: 'ט', 10: 'י',
    11: 'י"א', 12: 'י"ב', 13: 'י"ג', 14: 'י"ד', 15: 'ט"ו', 16: 'ט"ז', 17: 'י"ז', 18: 'י"ח', 19: 'י"ט', 20: 'כ',
    21: 'כ"א', 22: 'כ"ב', 23: 'כ"ג', 24: 'כ"ד', 25: 'כ"ה', 26: 'כ"ו', 27: 'כ"ז', 28: 'כ"ח', 29: 'כ"ט', 30: 'ל'
  };

  const days: RambamDay[] = dailyTasks.map((task, index) => {
    const dayNum = startHebDay + index;
    return {
      id: `${id}-${dayNum}`,
      hebrewDay: HEB_NUMERALS[dayNum] || dayNum.toString(),
      ...task
    };
  });

  return { id, name, year, days };
}

// ==========================================
// CYCLE 46 (3 CHAPTERS) - 339 DAYS
// Starts 16 Shevat 5786
// ==========================================

export const SCHEDULE_3_CH: RambamMonth[] = [
  generateMonth('shevat-5786', 'שבט', "ה'תשפ\"ו", 15, 16, [
    { subject: 'הקדמה', chapters: 'הקדמה', hideLabel: true },
    { subject: 'מצוות עשה', chapters: 'מצוות עשה: א-רמח', hideLabel: true },
    { subject: 'מצוות לא תעשה', chapters: 'מצוות לא תעשה: א-שסה', hideLabel: true },
    { subject: 'וראיתי לחלק', chapters: 'וראיתי לחלק', hideLabel: true },
    { subject: 'מדע: יסודי התורה', chapters: 'א-ג' },
    { subject: 'יסודי התורה', chapters: 'ד-ו' },
    { subject: 'יסודי התורה', chapters: 'ז-ט' },
    { subject: 'יסודי התורה / דעות', chapters: 'י / א-ב' },
    { subject: 'דעות', chapters: 'ג-ה' },
    { subject: 'דעות / תלמוד תורה', chapters: 'ו-ז / א' },
    { subject: 'תלמוד תורה', chapters: 'ב-ד' },
    { subject: 'תלמוד תורה', chapters: 'ה-ז' },
    { subject: 'עבודה זרה', chapters: 'א-ג' },
    { subject: 'עבודה זרה', chapters: 'ד-ו' },
    { subject: 'עבודה זרה', chapters: 'ז-ט' },
  ]),
  generateMonth('adar-5786', 'אדר', "ה'תשפ\"ו", 29, 1, [
    { subject: 'עבודה זרה', chapters: 'י-יב' },
    { subject: 'תשובה', chapters: 'א-ג' },
    { subject: 'תשובה', chapters: 'ד-ו' },
    { subject: 'תשובה', chapters: 'ז-ט' },
    { subject: 'תשובה / אהבה: ק"ש', chapters: 'י / א-ב' },
    { subject: 'קריאת שמע / תפילה', chapters: 'ג-ד / א' },
    { subject: 'תפילה', chapters: 'ב-ד' },
    { subject: 'תפילה', chapters: 'ה-ז' },
    { subject: 'תפילה', chapters: 'ח-י' },
    { subject: 'תפילה', chapters: 'יא-יג' },
    { subject: 'תפילה / תפילין ומזוזה וס"ת', chapters: 'יד-טו / א' },
    { subject: 'תפילין ומזוזה וס"ת', chapters: 'ב-ד' },
    { subject: 'תפילין ומזוזה וס\"ת', chapters: 'ה-ז' },
    { subject: 'תפילין ומזוזה וס\"ת', chapters: 'ח-י' },
    { subject: 'ציצית', chapters: 'א-ג' },
    { subject: 'ברכות', chapters: 'א-ג' },
    { subject: 'ברכות', chapters: 'ד-ו' },
    { subject: 'ברכות', chapters: 'ז-ט' },
    { subject: 'ברכות / מילה', chapters: 'י-יא / א' },
    { subject: 'מילה / סדר תפלות', chapters: 'ב-ג / חלק א' },
    { subject: 'סדר תפלות כל השנה', chapters: 'חלק ב' },
    { subject: 'סדר תפלות כל השנה / זמנים: שבת', chapters: 'חלק ג / א-ב' },
    { subject: 'שבת', chapters: 'ג-ה' },
    { subject: 'שבת', chapters: 'ו-ח' },
    { subject: 'שבת', chapters: 'ט-יא' },
    { subject: 'שבת', chapters: 'יב-יד' },
    { subject: 'שבת', chapters: 'טו-יז' },
    { subject: 'שבת', chapters: 'יח-כ' },
    { subject: 'שבת', chapters: 'כא-כג' },
  ]),
  generateMonth('nisan-5786', 'ניסן', "ה'תשפ\"ו", 30, 1, [
    { subject: 'שבת', chapters: 'כד-כו' },
    { subject: 'שבת', chapters: 'כז-כט' },
    { subject: 'שבת / עירובין', chapters: 'ל / א-ב' },
    { subject: 'עירובין', chapters: 'ג-ה' },
    { subject: 'עירובין', chapters: 'ו-ח' },
    { subject: 'שביתת עשור', chapters: 'א-ג' },
    { subject: 'שביתת יום טוב', chapters: 'א-ג' },
    { subject: 'שביתת יום טוב', chapters: 'ד-ו' },
    { subject: 'שביתת יום טוב / חמץ ומצה', chapters: 'ז-ח / א' },
    { subject: 'חמץ ומצה', chapters: 'ב-ד' },
    { subject: 'חמץ ומצה', chapters: 'ה-ז' },
    { subject: 'חמץ ומצה / שופר סוכה ולולב', chapters: 'ח / א-ב' },
    { subject: 'שופר סוכה ולולב', chapters: 'ג-ה' },
    { subject: 'שופר סוכה ולולב', chapters: 'ו-ח' },
    { subject: 'שקלים', chapters: 'א-ג' },
    { subject: 'שקלים / קידוש החודש', chapters: 'ד / א-ב' },
    { subject: 'קידוש החודש', chapters: 'ג-ה' },
    { subject: 'קידוש החודש', chapters: 'ו-ח' },
    { subject: 'קידוש החודש', chapters: 'ט-יא' },
    { subject: 'קידוש החודש', chapters: 'יב-יד' },
    { subject: 'קידוש החודש', chapters: 'טו-יז' },
    { subject: 'קידוש החודש / תעניות', chapters: 'יח-יט / א' },
    { subject: 'תעניות', chapters: 'ב-ד' },
    { subject: 'תעניות / מגילה וחנוכה', chapters: 'ה / א-ב' },
    { subject: 'מגילה וחנוכה / נשים: אישות', chapters: 'ג-ד / א' },
    { subject: 'אישות', chapters: 'ב-ד' },
    { subject: 'אישות', chapters: 'ה-ז' },
    { subject: 'אישות', chapters: 'ח-י' },
    { subject: 'אישות', chapters: 'יא-יג' },
    { subject: 'אישות', chapters: 'יד-טז' },
  ]),
  generateMonth('iyar-5786', 'אייר', "ה'תשפ\"ו", 29, 1, [
    { subject: 'אישות', chapters: 'יז-יט' },
    { subject: 'אישות', chapters: 'כ-כב' },
    { subject: 'אישות', chapters: 'כג-כה' },
    { subject: 'גירושין', chapters: 'א-ג' },
    { subject: 'גירושין', chapters: 'ד-ו' },
    { subject: 'גירושין', chapters: 'ז-ט' },
    { subject: 'גירושין', chapters: 'י-יב' },
    { subject: 'גירושין / יבום וחליצה', chapters: 'יג / א-ב' },
    { subject: 'יבום וחליצה', chapters: 'ג-ה' },
    { subject: 'יבום וחליצה', chapters: 'ו-ח' },
    { subject: 'יבום וחליצה / נערה בתולה', chapters: 'ט-יא / א' },
    { subject: 'נערה בתולה / סוטה', chapters: 'ב-ג / א' },
    { subject: 'סוטה / קדושה: איסורי ביאה', chapters: 'ב-ד / א' },
    { subject: 'איסורי ביאה', chapters: 'ב-ד' },
    { subject: 'איסורי ביאה', chapters: 'ה-ז' },
    { subject: 'איסורי ביאה', chapters: 'ח-י' },
    { subject: 'איסורי ביאה', chapters: 'יא-יג' },
    { subject: 'איסורי ביאה', chapters: 'יד-טז' },
    { subject: 'איסורי ביאה', chapters: 'יז-יט' },
    { subject: 'איסורי ביאה / מאכלות אסורות', chapters: 'כ-כב / א' },
    { subject: 'מאכלות אסורות', chapters: 'ב-ד' },
    { subject: 'מאכלות אסורות', chapters: 'ה-ז' },
    { subject: 'מאכלות אסורות', chapters: 'ח-י' },
    { subject: 'מאכלות אסורות', chapters: 'יא-יג' },
    { subject: 'מאכלות אסורות', chapters: 'יד-טז' },
    { subject: 'מאכלות אסורות / שחיטה', chapters: 'יז / א-ב' },
    { subject: 'שחיטה', chapters: 'ג-ה' },
    { subject: 'שחיטה', chapters: 'ו-ח' },
    { subject: 'שחיטה', chapters: 'ט-יא' },
  ]),
  generateMonth('sivan-5786', 'סיון', "ה'תשפ\"ו", 30, 1, [
    { subject: 'שחיטה', chapters: 'יב-יד' },
    { subject: 'הפלאה: שבועות', chapters: 'א-ג' },
    { subject: 'שבועות', chapters: 'ד-ו' },
    { subject: 'שבועות', chapters: 'ז-ט' },
    { subject: 'שבועות', chapters: 'י-יב' },
    { subject: 'נדרים', chapters: 'א-ג' },
    { subject: 'נדרים', chapters: 'ד-ו' },
    { subject: 'נדרים', chapters: 'ז-ט' },
    { subject: 'נדרים', chapters: 'י-יב' },
    { subject: 'נדרים / נזירות', chapters: 'יג / א-ב' },
    { subject: 'נזירות', chapters: 'ג-ה' },
    { subject: 'נזירות', chapters: 'ו-ח' },
    { subject: 'נזירות / ערכין וחרמין', chapters: 'ט-י / א' },
    { subject: 'ערכין וחרמין', chapters: 'ב-ד' },
    { subject: 'ערכין וחרמין', chapters: 'ה-ז' },
    { subject: 'ערכין וחרמין / זרעים: כלאים', chapters: 'ח / א-ב' },
    { subject: 'כלאים', chapters: 'ג-ה' },
    { subject: 'כלאים', chapters: 'ו-ח' },
    { subject: 'כלאים / מתנות עניים', chapters: 'ט-י / א' },
    { subject: 'מתנות עניים', chapters: 'ב-ד' },
    { subject: 'מתנות עניים', chapters: 'ה-ז' },
    { subject: 'מתנות עניים', chapters: 'ח-י' },
    { subject: 'תרומות', chapters: 'א-ג' },
    { subject: 'תרומות', chapters: 'ד-ו' },
    { subject: 'תרומות', chapters: 'ז-ט' },
    { subject: 'תרומות', chapters: 'י-יב' },
    { subject: 'תרומות', chapters: 'יג-טו' },
    { subject: 'מעשר', chapters: 'א-ג' },
    { subject: 'מעשר', chapters: 'ד-ו' },
    { subject: 'מעשר', chapters: 'ז-ט' },
  ]),
  generateMonth('tammuz-5786', 'תמוז', "ה'תשפ\"ו", 29, 1, [
    { subject: 'מעשר', chapters: 'י-יב' },
    { subject: 'מעשר / מעשר שני', chapters: 'יג-יד / א' },
    { subject: 'מעשר שני', chapters: 'ב-ד' },
    { subject: 'מעשר שני', chapters: 'ה-ז' },
    { subject: 'מעשר שני', chapters: 'ח-י' },
    { subject: 'מעשר שני / ביכורים', chapters: 'יא / א-ב' },
    { subject: 'ביכורים', chapters: 'ג-ה' },
    { subject: 'ביכורים', chapters: 'ו-ח' },
    { subject: 'ביכורים', chapters: 'ט-יא' },
    { subject: 'ביכורים / שמיטה ויובל', chapters: 'יב / א-ב' },
    { subject: 'שמיטה ויובל', chapters: 'ג-ה' },
    { subject: 'שמיטה ויובל', chapters: 'ו-ח' },
    { subject: 'שמיטה ויובל', chapters: 'ט-יא' },
    { subject: 'שמיטה ויובל / עבודה: בית הבחירה', chapters: 'יב-יג / א' },
    { subject: 'בית הבחירה', chapters: 'ב-ד' },
    { subject: 'בית הבחירה', chapters: 'ה-ז' },
    { subject: 'בית הבחירה / כלי המקדש', chapters: 'ח / א-ב' },
    { subject: 'כלי המקדש', chapters: 'ג-ה' },
    { subject: 'כלי המקדש', chapters: 'ו-ח' },
    { subject: 'כלי המקדש / ביאת המקדש', chapters: 'ט-י / א' },
    { subject: 'ביאת המקדש', chapters: 'ב-ד' },
    { subject: 'ביאת המקדש', chapters: 'ה-ז' },
    { subject: 'ביאת המקדש / איסורי מזבח', chapters: 'ח-ט / א' },
    { subject: 'איסורי מזבח', chapters: 'ב-ד' },
    { subject: 'איסורי מזבח', chapters: 'ה-ז' },
    { subject: 'קרבנות: מעשי הקרבנות', chapters: 'א-ג' },
    { subject: 'מעשי הקרבנות', chapters: 'ד-ו' },
    { subject: 'מעשי הקרבנות', chapters: 'ז-ט' },
    { subject: 'מעשי הקרבנות', chapters: 'י-יב' },
  ]),
  generateMonth('av-5786', 'אב', "ה'תשפ\"ו", 30, 1, [
    { subject: 'מעשי הקרבנות', chapters: 'יג-טו' },
    { subject: 'מעשי הקרבנות', chapters: 'טז-יח' },
    { subject: 'מעשי הקרבנות / תמידין ומוספין', chapters: 'י"ט / א-ב' },
    { subject: 'תמידין ומוספין', chapters: 'ג-ה' },
    { subject: 'תמידין ומוספין', chapters: 'ו-ח' },
    { subject: 'תמידין ומוספין / פסולי המוקדשין', chapters: 'ט-י / א' },
    { subject: 'פסולי המוקדשין', chapters: 'ב-ד' },
    { subject: 'פסולי המוקדשין', chapters: 'ה-ז' },
    { subject: 'פסולי המוקדשין', chapters: 'ח-י' },
    { subject: 'פסולי המוקדשין', chapters: 'יא-יג' },
    { subject: 'פסולי המוקדשין', chapters: 'יד-טז' },
    { subject: 'פסולי המוקדשין', chapters: 'י"ז-י"ט' },
    { subject: 'עבודת יום הכפורים', chapters: 'א-ג' },
    { subject: 'עבודת יום הכפורים / מעילה', chapters: 'ד-ה / א' },
    { subject: 'מעילה', chapters: 'ב-ד' },
    { subject: 'מעילה', chapters: 'ה-ז' },
    { subject: 'מעילה / קרבנות: קרבן פסח', chapters: 'ח / א-ב' },
    { subject: 'קרבן פסח', chapters: 'ג-ה' },
    { subject: 'קרבן פסח', chapters: 'ו-ח' },
    { subject: 'קרבן פסח / חגיגה', chapters: 'ט-י / א' },
    { subject: 'חגיגה / בכורות', chapters: 'ב-ג / א' },
    { subject: 'בכורות', chapters: 'ב-ד' },
    { subject: 'בכורות', chapters: 'ה-ז' },
    { subject: 'בכורות / שגגות', chapters: 'ח / א-ב' },
    { subject: 'שגגות', chapters: 'ג-ה' },
    { subject: 'שגגות', chapters: 'ו-ח' },
    { subject: 'שגגות', chapters: 'ט-יא' },
    { subject: 'שגגות', chapters: 'יב-יד' },
    { subject: 'שגגות / מחוסרי כפרה', chapters: 'טו / א-ב' },
    { subject: 'מחוסרי כפרה', chapters: 'ג-ה' },
  ]),
  generateMonth('elul-5786', 'אלול', "ה'תשפ\"ו", 29, 1, [
    { subject: 'תמורה', chapters: 'א-ג' },
    { subject: 'תמורה / טהרה: טומאת מת', chapters: 'ד / א-ב' },
    { subject: 'טומאת מת', chapters: 'ג-ה' },
    { subject: 'טומאת מת', chapters: 'ו-ח' },
    { subject: 'טומאת מת', chapters: 'ט-יא' },
    { subject: 'טומאת מת', chapters: 'יב-יד' },
    { subject: 'טומאת מת', chapters: 'ט"ו-י"ז' },
    { subject: 'טומאת מת', chapters: 'י"ח-כ' },
    { subject: 'טומאת מת', chapters: 'כא-כג' },
    { subject: 'טומאת מת / פרה אדומה', chapters: 'כד-כה / א' },
    { subject: 'פרה אדומה', chapters: 'ב-ד' },
    { subject: 'פרה אדומה', chapters: 'ה-ז' },
    { subject: 'פרה אדומה', chapters: 'ח-י' },
    { subject: 'פרה אדומה', chapters: 'יא-יג' },
    { subject: 'פרה אדומה / טומאת צרעת', chapters: 'יד-טו / א' },
    { subject: 'טומאת צרעת', chapters: 'ב-ד' },
    { subject: 'טומאת צרעת', chapters: 'ה-ז' },
    { subject: 'טומאת צרעת', chapters: 'ח-י' },
    { subject: 'טומאת צרעת', chapters: 'יא-יג' },
    { subject: 'טומאת צרעת', chapters: 'יד-טז' },
    { subject: 'מטמאי משכב ומושב', chapters: 'א-ג' },
    { subject: 'מטמאי משכב ומושב', chapters: 'ד-ו' },
    { subject: 'מטמאי משכב ומושב', chapters: 'ז-ט' },
    { subject: 'מטמאי משכב ומושב', chapters: 'י-יב' },
    { subject: 'מטמאי משכב ומושב / שאר אבות הטומאות', chapters: 'יג / א-ב' },
    { subject: 'שאר אבות הטומאות', chapters: 'ג-ה' },
    { subject: 'שאר אבות הטומאות', chapters: 'ו-ח' },
    { subject: 'שאר אבות הטומאות', chapters: 'ט-יא' },
    { subject: 'שאר אבות הטומאות', chapters: 'יב-יד' },
  ]),
  generateMonth('tishrei-5787', 'תשרי', "ה'תשפ\"ז", 30, 1, [
    { subject: 'שאר אבות הטומאות', chapters: 'טו-יז' },
    { subject: 'שאר אבות הטומאות', chapters: 'יח-כ' },
    { subject: 'טומאת אוכלין', chapters: 'א-ג' },
    { subject: 'טומאת אוכלין', chapters: 'ד-ו' },
    { subject: 'טומאת אוכלין', chapters: 'ז-ט' },
    { subject: 'טומאת אוכלין', chapters: 'י-יב' },
    { subject: 'טומאת אוכלין', chapters: 'יג-טו' },
    { subject: 'טומאת אוכלין / כלים', chapters: 'טז / א-ב' },
    { subject: 'כלים', chapters: 'ג-ה' },
    { subject: 'כלים', chapters: 'ו-ח' },
    { subject: 'כלים', chapters: 'ט-יא' },
    { subject: 'כלים', chapters: 'יב-יד' },
    { subject: 'כלים', chapters: 'טו-יז' },
    { subject: 'כלים', chapters: 'יח-כ' },
    { subject: 'כלים', chapters: 'כא-כג' },
    { subject: 'כלים', chapters: 'כד-כו' },
    { subject: 'כלים / מקואות', chapters: 'כז-כח / א' },
    { subject: 'מקואות', chapters: 'ב-ד' },
    { subject: 'מקואות', chapters: 'ה-ז' },
    { subject: 'מקואות', chapters: 'ח-י' },
    { subject: 'נזיקין: מקואות / נזקי ממון', chapters: 'יא / א-ב' },
    { subject: 'נזקי ממון', chapters: 'ג-ה' },
    { subject: 'נזקי ממון', chapters: 'ו-ח' },
    { subject: 'נזקי ממון', chapters: 'ט-יא' },
    { subject: 'נזקי ממון', chapters: 'יב-יד' },
    { subject: 'גניבה', chapters: 'א-ג' },
    { subject: 'גניבה', chapters: 'ד-ו' },
    { subject: 'גניבה', chapters: 'ז-ט' },
    { subject: 'גזילה ואבידה', chapters: 'א-ג' },
    { subject: 'גזילה ואבידה', chapters: 'ד-ו' },
  ]),
  generateMonth('heshvan-5787', 'חשון', "ה'תשפ\"ז", 30, 1, [
    { subject: 'גזילה ואבידה', chapters: 'ז-ט' },
    { subject: 'גזילה ואבידה', chapters: 'י-יב' },
    { subject: 'גזילה ואבידה', chapters: 'יג-טו' },
    { subject: 'גזילה ואבידה', chapters: 'טז-יח' },
    { subject: 'חובל ומזיק', chapters: 'א-ג' },
    { subject: 'חובל ומזיק', chapters: 'ד-ו' },
    { subject: 'חובל ומזיק / רוצח ושמירת הנפש', chapters: 'ז-ח / א' },
    { subject: 'רוצח ושמירת נפש', chapters: 'ב-ד' },
    { subject: 'רוצח ושמירת נפש', chapters: 'ה-ז' },
    { subject: 'רוצח ושמירת נפש', chapters: 'ח-י' },
    { subject: 'רוצח ושמירת נפש', chapters: 'יא-יג' },
    { subject: 'קנין: מכירה', chapters: 'א-ג' },
    { subject: 'מכירה', chapters: 'ד-ו' },
    { subject: 'מכירה', chapters: 'ז-ט' },
    { subject: 'מכירה', chapters: 'י-יב' },
    { subject: 'מכירה', chapters: 'יג-טו' },
    { subject: 'מכירה', chapters: 'טז-יח' },
    { subject: 'מכירה', chapters: 'יט-כא' },
    { subject: 'מכירה', chapters: 'כב-כד' },
    { subject: 'מכירה', chapters: 'כה-כז' },
    { subject: 'מכירה', chapters: 'כח-ל' },
    { subject: 'זכיה ומתנה', chapters: 'א-ג' },
    { subject: 'זכיה ומתנה', chapters: 'ד-ו' },
    { subject: 'זכיה ומתנה', chapters: 'ז-ט' },
    { subject: 'זכיה ומתנה', chapters: 'י-יב' },
    { subject: 'שכנים', chapters: 'א-ג' },
    { subject: 'שכנים', chapters: 'ד-ו' },
    { subject: 'שכנים', chapters: 'ז-ט' },
    { subject: 'שכנים', chapters: 'י-יב' },
    { subject: 'שכנים / שלוחין ושותפין', chapters: 'יג-יד / א' },
  ]),
  generateMonth('kislev-5787', 'כסלו', "ה'תשפ\"ז", 30, 1, [
    { subject: 'שלוחין ושותפין', chapters: 'ב-ד' },
    { subject: 'שלוחין ושותפין', chapters: 'ה-ז' },
    { subject: 'שלוחין ושותפין', chapters: 'ח-י' },
    { subject: 'עבדים', chapters: 'א-ג' },
    { subject: 'עבדים', chapters: 'ד-ו' },
    { subject: 'עבדים', chapters: 'ז-ט' },
    { subject: 'משפטים: שכירות', chapters: 'א-ג' },
    { subject: 'שכירות', chapters: 'ד-ו' },
    { subject: 'שכירות', chapters: 'ז-ט' },
    { subject: 'שכירות', chapters: 'י-יב' },
    { subject: 'שכירות / שאלה ופקדון', chapters: 'יג / א-ב' },
    { subject: 'שאלה ופקדון', chapters: 'ג-ה' },
    { subject: 'שאלה ופקדון', chapters: 'ו-ח' },
    { subject: 'מלוה ולוה', chapters: 'א-ג' },
    { subject: 'מלוה ולוה', chapters: 'ד-ו' },
    { subject: 'מלוה ולוה', chapters: 'ז-ט' },
    { subject: 'מלוה ולוה', chapters: 'י-יב' },
    { subject: 'מלוה ולוה', chapters: 'יג-טו' },
    { subject: 'מלוה ולוה', chapters: 'טז-יח' },
    { subject: 'מלוה ולוה', chapters: 'יט-כא' },
    { subject: 'מלוה ולוה', chapters: 'כב-כד' },
    { subject: 'מלוה ולוה', chapters: 'כה-כז' },
    { subject: 'טוען ונטען', chapters: 'א-ג' },
    { subject: 'טוען ונטען', chapters: 'ד-ו' },
    { subject: 'טוען ונטען', chapters: 'ז-ט' },
    { subject: 'טוען ונטען', chapters: 'י-יב' },
    { subject: 'טוען ונטען', chapters: 'יג-טו' },
    { subject: 'טוען ונטען / נחלות', chapters: 'טז / א-ב' },
    { subject: 'נחלות', chapters: 'ג-ה' },
    { subject: 'נחלות', chapters: 'ו-ח' },
  ]),
  generateMonth('tevet-5787', 'טבת', "ה'תשפ\"ז", 28, 1, [
    { subject: 'נחלות', chapters: 'ט-יא' },
    { subject: 'שופטים: סנהדרין', chapters: 'א-ג' },
    { subject: 'סנהדרין', chapters: 'ד-ו' },
    { subject: 'סנהדרין', chapters: 'ז-ט' },
    { subject: 'סנהדרין', chapters: 'י-יב' },
    { subject: 'סנהדרין', chapters: 'יג-טו' },
    { subject: 'סנהדרין', chapters: 'טז-יח' },
    { subject: 'סנהדרין', chapters: 'יט-כא' },
    { subject: 'סנהדרין', chapters: 'כב-כד' },
    { subject: 'סנהדרין / עדות', chapters: 'כה-כו / א' },
    { subject: 'עדות', chapters: 'ב-ד' },
    { subject: 'עדות', chapters: 'ה-ז' },
    { subject: 'עדות', chapters: 'ח-י' },
    { subject: 'עדות', chapters: 'יא-יג' },
    { subject: 'עדות', chapters: 'יד-טז' },
    { subject: 'עדות', chapters: 'יז-יט' },
    { subject: 'עדות', chapters: 'כ-כב' },
    { subject: 'ממרים', chapters: 'א-ג' },
    { subject: 'ממרים', chapters: 'ד-ו' },
    { subject: 'ממרים / אבל', chapters: 'ז / א-ב' },
    { subject: 'אבל', chapters: 'ג-ה' },
    { subject: 'אבל', chapters: 'ו-ח' },
    { subject: 'אבל', chapters: 'ט-יא' },
    { subject: 'אבל', chapters: 'יב-יד' },
    { subject: 'מלכים ומלחמותיהם', chapters: 'א-ג' },
    { subject: 'מלכים ומלחמותיהם', chapters: 'ד-ו' },
    { subject: 'מלכים ומלחמותיהם', chapters: 'ז-ט' },
    { subject: 'מלכים ומלחמותיהם', chapters: 'י-יב' },
  ])
];

// ==========================================
// CYCLE 16 (1 CHAPTER) - 1017 DAYS
// 1000 Chapters + 12 Intro + 4 Tefilla + 1 Haggada
// Starts 16 Shevat 5786
// Ends 26 Cheshvan 5789
// ==========================================

const HEB = ["", "א", "ב", "ג", "ד", "ה", "ו", "ז", "ח", "ט", "י", "יא", "יב", "יג", "יד", "טו", "טז", "יז", "יח", "יט", "כ", "כא", "כב", "כג", "כד", "כה", "כו", "כז", "כח", "כט", "ל"];

// Helper to generate the list based on provided columns
const ALL_ITEMS_1_CH_RAW = [
  // Days 1-3
  { s: 'הקדמה', t: 'חלק', n: 'א' },
  { s: 'הקדמה', t: 'חלק', n: 'ב' },
  { s: 'הקדמה', t: 'חלק', n: 'ג' },
  // Days 4-6
  { s: 'מצוות עשה', t: 'מצוות עשה:', n: 'א-פג' },
  { s: 'מצוות עשה', t: 'מצוות עשה:', n: 'פד-קסו' },
  { s: 'מצוות עשה', t: 'מצוות עשה:', n: 'קסז-רמח' },
  // Days 7-9
  { s: 'מצוות לא תעשה', t: 'מצוות לא תעשה:', n: 'א-קכב' },
  { s: 'מצוות לא תעשה', t: 'מצוות לא תעשה:', n: 'קכג-רמד' },
  { s: 'מצוות לא תעשה', t: 'מצוות לא תעשה:', n: 'רמה-שסה' },
  // Days 10-12
  { s: 'וראיתי לחלק', t: 'חלק', n: 'א' },
  { s: 'וראיתי לחלק', t: 'חלק', n: 'ב' },
  { s: 'וראיתי לחלק', t: 'חלק', n: 'ג' },
  // Madda
  ...Array.from({ length: 10 }, (_, i) => ({ s: i === 0 ? 'מדע: יסודי התורה' : 'יסודי התורה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 7 }, (_, i) => ({ s: 'דעות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 7 }, (_, i) => ({ s: 'תלמוד תורה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 12 }, (_, i) => ({ s: 'עבודה זרה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 10 }, (_, i) => ({ s: 'תשובה', t: 'פרק', n: HEB[i + 1] })),
  // Ahava
  ...Array.from({ length: 4 }, (_, i) => ({ s: i === 0 ? 'אהבה: קריאת שמע' : 'קריאת שמע', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 15 }, (_, i) => ({ s: 'תפילה וברכת כהנים', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 10 }, (_, i) => ({ s: 'תפילין ומזוזה וס"ת', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 3 }, (_, i) => ({ s: 'ציצית', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 11 }, (_, i) => ({ s: 'ברכות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 3 }, (_, i) => ({ s: 'מילה', t: 'פרק', n: HEB[i + 1] })),
  // Seder Tefillot
  ...Array.from({ length: 4 }, (_, i) => ({ s: 'סדר תפילות כל השנה', t: 'חלק', n: HEB[i + 1] })),
  // Zmanim
  ...Array.from({ length: 30 }, (_, i) => ({ s: i === 0 ? 'זמנים: שבת' : 'שבת', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'עירובין', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 3 }, (_, i) => ({ s: 'שביתת עשור', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'יום טוב', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'חמץ ומצה', t: 'פרק', n: HEB[i + 1] })),
  // Haggada
  { s: 'נוסח ההגדה', t: 'נוסח ההגדה', n: '' },
  // Shofar
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'שופר סוכה ולולב', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 4 }, (_, i) => ({ s: 'שקלים', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 19 }, (_, i) => ({ s: 'קידוש החודש', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 5 }, (_, i) => ({ s: 'תעניות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 4 }, (_, i) => ({ s: 'מגילה וחנוכה', t: 'פרק', n: HEB[i + 1] })),
  // Nashim
  ...Array.from({ length: 25 }, (_, i) => ({ s: i === 0 ? 'נשים: אישות' : 'אישות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 13 }, (_, i) => ({ s: 'גירושין', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'יבום וחליצה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 3 }, (_, i) => ({ s: 'נערה בתולה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 4 }, (_, i) => ({ s: 'סוטה', t: 'פרק', n: HEB[i + 1] })),
  // Kedusha
  ...Array.from({ length: 22 }, (_, i) => ({ s: i === 0 ? 'קדושה: איסורי ביאה' : 'איסורי ביאה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 17 }, (_, i) => ({ s: 'מאכלות אסורות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 14 }, (_, i) => ({ s: 'שחיטה', t: 'פרק', n: HEB[i + 1] })),
  // Hafla'ah
  ...Array.from({ length: 12 }, (_, i) => ({ s: i === 0 ? 'הפלאה: שבועות' : 'שבועות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 13 }, (_, i) => ({ s: 'נדרים', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 10 }, (_, i) => ({ s: 'נזירות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'ערכין וחרמין', t: 'פרק', n: HEB[i + 1] })),
  // Zeraim
  ...Array.from({ length: 10 }, (_, i) => ({ s: i === 0 ? 'זרעים: כלאים' : 'כלאים', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 10 }, (_, i) => ({ s: 'מתנות עניים', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 15 }, (_, i) => ({ s: 'תרומות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 14 }, (_, i) => ({ s: 'מעשר', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 11 }, (_, i) => ({ s: 'מעשר שני ונטע רבעי', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 12 }, (_, i) => ({ s: 'ביכורים', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 13 }, (_, i) => ({ s: 'שמיטה ויובל', t: 'פרק', n: HEB[i + 1] })),
  // Avodah
  ...Array.from({ length: 8 }, (_, i) => ({ s: i === 0 ? 'עבודה: בית הבחירה' : 'בית הבחירה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 10 }, (_, i) => ({ s: 'כלי המקדש', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 9 }, (_, i) => ({ s: 'ביאת המקדש', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 7 }, (_, i) => ({ s: 'איסורי מזבח', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 19 }, (_, i) => ({ s: 'מעשה הקרבנות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 10 }, (_, i) => ({ s: 'תמידין ומוספין', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 19 }, (_, i) => ({ s: 'פסולי המוקדשין', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 5 }, (_, i) => ({ s: 'עבודת יוה"כ', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'מעילה', t: 'פרק', n: HEB[i + 1] })),
  // Korbanot
  ...Array.from({ length: 10 }, (_, i) => ({ s: i === 0 ? 'קרבנות: קרבן פסח' : 'קרבן פסח', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 3 }, (_, i) => ({ s: 'חגיגה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'בכורות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 15 }, (_, i) => ({ s: 'שגגות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 5 }, (_, i) => ({ s: 'מחוסרי כפרה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 4 }, (_, i) => ({ s: 'תמורה', t: 'פרק', n: HEB[i + 1] })),
  // Tahara
  ...Array.from({ length: 25 }, (_, i) => ({ s: i === 0 ? 'טהרה: טומאת מת' : 'טומאת מת', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 15 }, (_, i) => ({ s: 'פרה אדומה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 16 }, (_, i) => ({ s: 'טומאת צרעת', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 13 }, (_, i) => ({ s: 'מטמאי משכב ומושב', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 20 }, (_, i) => ({ s: 'שאר אבות הטומאות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 16 }, (_, i) => ({ s: 'טומאת אוכלין', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 28 }, (_, i) => ({ s: 'כלים', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 11 }, (_, i) => ({ s: 'מקואות', t: 'פרק', n: HEB[i + 1] })),
  // Nezikin
  ...Array.from({ length: 14 }, (_, i) => ({ s: i === 0 ? 'נזיקין: נזקי ממון' : 'נזקי ממון', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 9 }, (_, i) => ({ s: 'גניבה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 18 }, (_, i) => ({ s: 'גזילה ואבידה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'חובל ומזיק', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 13 }, (_, i) => ({ s: 'רוצח ושמירת נפש', t: 'פרק', n: HEB[i + 1] })),
  // Kinyan
  ...Array.from({ length: 30 }, (_, i) => ({ s: i === 0 ? 'קנין: מכירה' : 'מכירה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 12 }, (_, i) => ({ s: 'זכיה ומתנה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 14 }, (_, i) => ({ s: 'שכנים', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 10 }, (_, i) => ({ s: 'שלוחין ושותפין', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 9 }, (_, i) => ({ s: 'עבדים', t: 'פרק', n: HEB[i + 1] })),
  // Mishpatim
  ...Array.from({ length: 13 }, (_, i) => ({ s: i === 0 ? 'משפטים: שכירות' : 'שכירות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 8 }, (_, i) => ({ s: 'שאלה ופקדון', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 27 }, (_, i) => ({ s: 'מלווה ולווה', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 16 }, (_, i) => ({ s: 'טוען ונטען', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 11 }, (_, i) => ({ s: 'נחלות', t: 'פרק', n: HEB[i + 1] })),
  // Shoftim
  ...Array.from({ length: 26 }, (_, i) => ({ s: i === 0 ? 'שופטים: סנהדרין' : 'סנהדרין', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 22 }, (_, i) => ({ s: 'עדות', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 7 }, (_, i) => ({ s: 'ממרים', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 14 }, (_, i) => ({ s: 'אבל', t: 'פרק', n: HEB[i + 1] })),
  ...Array.from({ length: 12 }, (_, i) => ({ s: 'מלכים ומלחמותיהם', t: 'פרק', n: HEB[i + 1] })),
];

const ALL_ITEMS_1_CH = ALL_ITEMS_1_CH_RAW.map(item => ({
  subject: item.s,
  chapters: `${item.t}${item.n ? ' ' + item.n : ''}`,
  hideLabel: true
}));

function buildScheduleOneCh() {
  const result: RambamMonth[] = [];
  let itemIdx = 0;

  const monthDefinitions = [
    // 5786 (starts 16 Shevat)
    { id: 'shevat-5786', name: 'שבט', year: "ה'תשפ\"ו", days: 15, start: 16 },
    { id: 'adar-5786', name: 'אדר', year: "ה'תשפ\"ו", days: 29, start: 1 },
    { id: 'nisan-5786', name: 'ניסן', year: "ה'תשפ\"ו", days: 30, start: 1 },
    { id: 'iyar-5786', name: 'אייר', year: "ה'תשפ\"ו", days: 29, start: 1 },
    { id: 'sivan-5786', name: 'סיון', year: "ה'תשפ\"ו", days: 30, start: 1 },
    { id: 'tammuz-5786', name: 'תמוז', year: "ה'תשפ\"ו", days: 29, start: 1 },
    { id: 'av-5786', name: 'אב', year: "ה'תשפ\"ו", days: 30, start: 1 },
    { id: 'elul-5786', name: 'אלול', year: "ה'תשפ\"ו", days: 29, start: 1 },
    // 5787
    { id: 'tishrei-5787', name: 'תשרי', year: "ה'תשפ\"ז", days: 30, start: 1 },
    { id: 'heshvan-5787', name: 'חשון', year: "ה'תשפ\"ז", days: 30, start: 1 },
    { id: 'kislev-5787', name: 'כסלו', year: "ה'תשפ\"ז", days: 30, start: 1 },
    { id: 'tevet-5787', name: 'טבת', year: "ה'תשפ\"ז", days: 29, start: 1 },
    { id: 'shevat-5787', name: 'שבט', year: "ה'תשפ\"ז", days: 30, start: 1 },
    { id: 'adar-i-5787', name: 'אדר א׳', year: "ה'תשפ\"ז", days: 30, start: 1 },
    { id: 'adar-ii-5787', name: 'אדר ב׳', year: "ה'תשפ\"ז", days: 29, start: 1 },
    { id: 'nisan-5787', name: 'ניסן', year: "ה'תשפ\"ז", days: 30, start: 1 },
    { id: 'iyar-5787', name: 'אייר', year: "ה'תשפ\"ז", days: 29, start: 1 },
    { id: 'sivan-5787', name: 'סיון', year: "ה'תשפ\"ז", days: 30, start: 1 },
    { id: 'tammuz-5787', name: 'תמוז', year: "ה'תשפ\"ז", days: 29, start: 1 },
    { id: 'av-5787', name: 'אב', year: "ה'תשפ\"ז", days: 30, start: 1 },
    { id: 'elul-5787', name: 'אלול', year: "ה'תשפ\"ז", days: 29, start: 1 },
    // 5788
    { id: 'tishrei-5788', name: 'תשרי', year: "ה'תשפ\"ח", days: 30, start: 1 },
    { id: 'heshvan-5788', name: 'חשון', year: "ה'תשפ\"ח", days: 30, start: 1 },
    { id: 'kislev-5788', name: 'כסלו', year: "ה'תשפ\"ח", days: 30, start: 1 },
    { id: 'tevet-5788', name: 'טבת', year: "ה'תשפ\"ח", days: 29, start: 1 },
    { id: 'shevat-5788', name: 'שבט', year: "ה'תשפ\"ח", days: 30, start: 1 },
    { id: 'adar-5788', name: 'אדר', year: "ה'תשפ\"ח", days: 29, start: 1 },
    { id: 'nisan-5788', name: 'ניסן', year: "ה'תשפ\"ח", days: 30, start: 1 },
    { id: 'iyar-5788', name: 'אייר', year: "ה'תשפ\"ח", days: 29, start: 1 },
    { id: 'sivan-5788', name: 'סיון', year: "ה'תשפ\"ח", days: 30, start: 1 },
    { id: 'tammuz-5788', name: 'תמוז', year: "ה'תשפ\"ח", days: 29, start: 1 },
    { id: 'av-5788', name: 'אב', year: "ה'תשפ\"ח", days: 30, start: 1 },
    { id: 'elul-5788', name: 'אלול', year: "ה'תשפ\"ח", days: 29, start: 1 },
    // 5789
    { id: 'tishrei-5789', name: 'תשרי', year: "ה'תשפ\"ט", days: 30, start: 1 },
    { id: 'heshvan-5789', name: 'חשון', year: "ה'תשפ\"ט", days: 26, start: 1 },
  ];

  for (const def of monthDefinitions) {
    const monthItems = ALL_ITEMS_1_CH.slice(itemIdx, itemIdx + def.days);
    result.push(generateMonth(def.id, def.name, def.year, def.days, def.start, monthItems));
    itemIdx += def.days;
  }
  return result;
}

export const SCHEDULE_1_CH: RambamMonth[] = buildScheduleOneCh();
